export const usersMock = [
  {
    firstname: "Moch",
    lastname: "Blagoo",
    position: "CEO",
    phone: "85112341234",
    email: "moch.blagoo@gmail.com",
  },
  {
    firstname: "Sopan",
    lastname: "Sofian",
    position: "CTO",
    phone: "85644441234",
    email: "sopan.sofian@gmail.com",
  },
  {
    firstname: "John",
    lastname: "Doe",
    position: "Software Engineer",
    phone: "85755551234",
    email: "john.doe@gmail.com",
  },
  {
    firstname: "Jane",
    lastname: "Doe",
    position: "Graphic Designer",
    phone: "85966661234",
    email: "jane.doe@gmail.com",
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    position: "HR Manager",
    phone: "85877771234",
    email: "alice.smith@gmail.com",
  },
  {
    firstname: "Bob",
    lastname: "Johnson",
    position: "Marketing Manager",
    phone: "85788881234",
    email: "bob.johnson@gmail.com",
  },
  {
    firstname: "Emily",
    lastname: "Davis",
    position: "Project Manager",
    phone: "85999991234",
    email: "emily.davis@gmail.com",
  },
  {
    firstname: "Michael",
    lastname: "Clark",
    position: "Financial Analyst",
    phone: "85610101234",
    email: "michael.clark@gmail.com",
  },
  {
    firstname: "Sarah",
    lastname: "Wilson",
    position: "Sales Representative",
    phone: "85111111234",
    email: "sarah.wilson@gmail.com",
  },
  {
    firstname: "David",
    lastname: "Lee",
    position: "Product Manager",
    phone: "85121231234",
    email: "david.lee@gmail.com",
  },
  {
    firstname: "Jessica",
    lastname: "Taylor",
    position: "Customer Support",
    phone: "85131341234",
    email: "jessica.taylor@gmail.com",
  },
  {
    firstname: "Matthew",
    lastname: "Brown",
    position: "Operations Manager",
    phone: "85241451234",
    email: "matthew.brown@gmail.com",
  },
];
